language: node_js

node_js:
- 8.9.4

cache:
  directories:
  - node_modules

before_install:
  - npm install -g webpack
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then source /.env-dev.sh; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then source /.env-master.sh; fi

install:
  - cd frontend
  - npm install
  - npm run build_travis
  - cd ..
  - mv backend/* .
  - npm install

script:
- npm run test

deploy:
  - provider: s3
    skip_cleanup: true
    detect_encoding: true
    access_key_id: $ACCESS_KEY_ID_current
    secret_access_key: $SECRET_ACCESS_KEY_current
    bucket: $BUCKET_current
    local-dir: frontend/build
    acl: bucket_owner_full_control
    on:
      repo: GLO3112-H18/ugram-team-06
      condition: $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "dev"
      branch: $TRAVIS_BRANCH

  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID_dev
    secret_access_key: $SECRET_ACCESS_KEY_dev
    region: "us-east-2"
    app: "ugram"
    env: "ugram-env"
    zip_file: "ugram-api.zip"
    skip_cleanup: true
    bucket_name: "elasticbeanstalk-us-east-2-977610490635"
    on:
        repo: GLO3112-H18/ugram-team-06
        branch: $TRAVIS_BRANCH

notifications:
  slack:
    secure: GJeNtiRvJhqte6TiTiCswsYR4IAWx62IcsveWXijoqG79hr8fMEwP8cOGajCpa9P7/Lua332CJhsVhVkZ8d/tig9ELXQTXN3zq8l8a2ld/a99btx1XcFqFG7WqFvp9WZcYUxERdl1tZG0gV03v7uNptHtpi8M+4ECfkwDImwwjsuKGBpmUkq52qKWA/m+WhsrOivDfVznV9/GNhG9RIyEnWr8aZ9E2SiW4i50g8UwSS2tig9K+VhzKWSrim6ed80aWKEMMrCGcgf4bxOnxDTs03xcby/OqO1v6ap1JF0EH1mcUbDmk4T7ZWMuOiIFEQM0m87jrKYc/bXQLxWILPlZySYyrilcCpJdTABM+rhu+hepOfPa3DeHd15l/XAjJkoRJzwzIUd0E2G0xSuZkrYti23nfIr8qekaZqsYHbdpaUs8GHUkUco9gTjGjXM72cxAsSc75C3MvHnFuYvQLoq+G59Dwucl8ImG6HmcSyo8elr6aia+9NAir6hqBe9Y9kDa9qGx4Mfce9EgJ2jHFQsy0yJ/L0WC0k5NO8LijNPqews7SZCiouo8lQP1Cf0uLgOhOfItLWbVhiNduKE7YhZA0zY8G9UdMAoZgLsJfrQ4eS/6u7DRf5UQgPh9aUv0cI4K74+ijYnfvDM4fyjfVqB56ryoely9Aocn08xlUFHX2k=
