language: node_js

node_js:
- 8.9.4

cache:
  directories:
  - node_modules

before_install:
- cd frontend

before_script:
- npm install -g webpack

script: 
  -npm run build

deploy:
  provider: s3
  access_key_id: AKIAJLOBPV7PIJMR7CRA
  secret_access_key:
    secure: MeYeFv4Luo2lnsvudFs9kGlHk+5KHMNWkQBh2Md4aDRXhXf0jVuEefMYIi7/oWDFo0KFTPt3sT+GDYuG8YRt001dHGT6lJ/viK2vbMSBRxKhjgbQfu2CyP+Hl0zs8VAnEWeB1B4zzdzj8umBBnc4egIqylxek4pEWK8BWS0fOUkbF44qplDD9QtGNPV0uL+nbjwnKBelUd9qtKomzdCJ1CCH97f0dnVikSzoulWbXBkK6SzdC+8/uQljBF1Yw5nyDPiwhsB2Eojim00G3nWfbKYNM6AgdKE/qaYrmv/eBzc1e/eOxCuilWQneCfHCNAwbF7IAOWhKk2bdmccUPRy0A/xo1vHuaoxBLnRjXQVNagOCwlXciGncZb8vCHpsdXyKSotjNPp2qn0zvENV79lhQj6MrTwcZKGyWz/q2iha5ZLS35Ww7P3FdPmUb9sEyH6FyjgcTEYnBzXTNCdKhCTc+x6PCq1qjhqWOUpe5L9qSBrLMr5A4DMMOzcIM172QL0TSjdfAlXezxTDanbQFPQZLlxMGAOKgWOMrozsUHjWm8/LMQatnIaAqzFzjc+UudJHzfunXRFMmDJ7p64VPR6ydF2LpT9Jx6TUT4yZKOUlxokHI3WpwqRaAiLNEKARf5mab3ePZ670nf7xonIK9Fy+mFODsaikO6m6Xcq6ug8fF4=
  bucket: ugram-dev
  local-dir: build
  acl: bucket_owner_full_control
  on:
    repo: GLO3112-H18/ugram-team-06
    branch: dev

notifications:
  slack:
    secure: Nsx4KfRTrDHX+nhXRjZIC68PKTZnblcSU3tIAIK1XTFgrLz7eWFmDpZs76k/DyxhUZrbSBrD08n/9/RTpCEDu55062yawg3WZWk/sdazQIErsghicb/7LUw2lBMDjArBUYDFvJ6km73AfUskkiINUZ2/QE5qELjhxzkvu6HSqV5e7IIaWQLeCu8YOIWocnjXlOOnGFW1Bgwn4Bp7CjX+1lZ8fni72E2oz46iuLVv/VYADaIBg2+YMcJXTUvpB/hDdwXso/a03KY9BpA8+AcHUn+ChEhizcRaaDDOAgPSM9iOlyPfzknJ/Lvj+RXl10f89gweJzociioGsQUdJRK171PDMGQ9j2lz2dFBnaL/EfFJbr7JmWV7fSOGPpbhocF/e1tj0oYxRlXq4dbbWjyGZ/MeAEKw1cwElGN/DeQgOijbvxxl0C5HGdYgY+oU7/tHTN2t/dMQ3pX/3E/iLlLzVLsDmPLfPkydj1xBHPhsOdLnCavT3PZTeC7i/nv+vOPt5YkoY4m38+aPbLyTygP/d9kkoKJBOAaZXLjqXMqsCVVYQvilSGb2Etb0rj63xxaRqquo4D+Hgv0wiIpO1W6mZCPY3IA8h1M5Yy+OMmsAR8BIqdzm3Fbzel8rvF/w3QVGwoRZXVm4tb5ST+ACBef/5bD02pmMUOAtAokxsXj8gCc=
