language: node_js

node_js:
- 8.9.4

cache:
  directories:
  - node_modules

before_install:
- cd frontend

before_script:
- npm install -g webpack

script:
- npm run build_travis

before_deploy:
- ls
- sh ./.travis.sh
- env

deploy:
  - provider: s3
    skip_cleanup: true
    detect_encoding: true
    access_key_id: AKIAJGCNW64MPWIIRYQQ
    secret_access_key:
      secure: peZ8UVc4ryS8ohwGBQJWRnx9Amuf1vymF+EoEU8vFKj5tm673ijXYzWptXegMr++2SN8QM7Dk1FRthVplMmeiZuCrVtax6x5q7Pory0fOmPns0MUJCnauOlVTk6hvNyLQK5knCbIQHCDDK6U3+xJdTHpV1OJvaqsMP8vZwvS66cJKC0UYVVud8qWKYY3vt/eq1BtUtGMGrQW2/dihF+vc9/mrAlACeoeLDhdwIdAbGl1O5zVMB28CRtP7vJOoxNX1Z+fL4IzglYnvfstb3YlefFGT6clrc+NhzLRp3hEcDPzKRmp4Iyc3OrV2NKLxjkDpFbBy/32otjAoS1C6nH+hSelgU+tcbERcDR6r4n27I5CU1FHYa83y2lTjoQQRj18TaY9daOoeaVYwey6qUPA0164Ku6O68IlbFeEnZLR5kaVyCsGig3saxwkxBEntFwNn1/itMx3YEV8LOBoVSY8d3jDEnW+tqyFSgE3qpFcXv2/PSMt/CvxkCgubD78To26LaMBvgKI4z+lh0ddfo4q8TB3rfmQvJEqTGvSi4x/sFOhksESzrsFWALfJxrySfCIMlp/bTXzJW85VpJLJABigO0qhtqXexnTAoZ6hgnYwgsS8UaGjMvL4vV/fSmCOmDZ5+zbWF1tmMg8pm9bwSlRqQHgJ6hVXVt5j1JE7owFE6I=
    bucket: ugram-prod
    local-dir: build
    acl: bucket_owner_full_control
    on:
      repo: GLO3112-H18/ugram-team-06
      branch: master

  - provider: s3
    skip_cleanup: true
    detect_encoding: true
    access_key_id: AKIAJLOBPV7PIJMR7CRA
    secret_access_key:
      secure: MeYeFv4Luo2lnsvudFs9kGlHk+5KHMNWkQBh2Md4aDRXhXf0jVuEefMYIi7/oWDFo0KFTPt3sT+GDYuG8YRt001dHGT6lJ/viK2vbMSBRxKhjgbQfu2CyP+Hl0zs8VAnEWeB1B4zzdzj8umBBnc4egIqylxek4pEWK8BWS0fOUkbF44qplDD9QtGNPV0uL+nbjwnKBelUd9qtKomzdCJ1CCH97f0dnVikSzoulWbXBkK6SzdC+8/uQljBF1Yw5nyDPiwhsB2Eojim00G3nWfbKYNM6AgdKE/qaYrmv/eBzc1e/eOxCuilWQneCfHCNAwbF7IAOWhKk2bdmccUPRy0A/xo1vHuaoxBLnRjXQVNagOCwlXciGncZb8vCHpsdXyKSotjNPp2qn0zvENV79lhQj6MrTwcZKGyWz/q2iha5ZLS35Ww7P3FdPmUb9sEyH6FyjgcTEYnBzXTNCdKhCTc+x6PCq1qjhqWOUpe5L9qSBrLMr5A4DMMOzcIM172QL0TSjdfAlXezxTDanbQFPQZLlxMGAOKgWOMrozsUHjWm8/LMQatnIaAqzFzjc+UudJHzfunXRFMmDJ7p64VPR6ydF2LpT9Jx6TUT4yZKOUlxokHI3WpwqRaAiLNEKARf5mab3ePZ670nf7xonIK9Fy+mFODsaikO6m6Xcq6ug8fF4=
    bucket: ugram-dev
    local-dir: build
    acl: bucket_owner_full_control
    on:
      repo: GLO3112-H18/ugram-team-06
      branch: dev

notifications:
  slack:
    secure: GJeNtiRvJhqte6TiTiCswsYR4IAWx62IcsveWXijoqG79hr8fMEwP8cOGajCpa9P7/Lua332CJhsVhVkZ8d/tig9ELXQTXN3zq8l8a2ld/a99btx1XcFqFG7WqFvp9WZcYUxERdl1tZG0gV03v7uNptHtpi8M+4ECfkwDImwwjsuKGBpmUkq52qKWA/m+WhsrOivDfVznV9/GNhG9RIyEnWr8aZ9E2SiW4i50g8UwSS2tig9K+VhzKWSrim6ed80aWKEMMrCGcgf4bxOnxDTs03xcby/OqO1v6ap1JF0EH1mcUbDmk4T7ZWMuOiIFEQM0m87jrKYc/bXQLxWILPlZySYyrilcCpJdTABM+rhu+hepOfPa3DeHd15l/XAjJkoRJzwzIUd0E2G0xSuZkrYti23nfIr8qekaZqsYHbdpaUs8GHUkUco9gTjGjXM72cxAsSc75C3MvHnFuYvQLoq+G59Dwucl8ImG6HmcSyo8elr6aia+9NAir6hqBe9Y9kDa9qGx4Mfce9EgJ2jHFQsy0yJ/L0WC0k5NO8LijNPqews7SZCiouo8lQP1Cf0uLgOhOfItLWbVhiNduKE7YhZA0zY8G9UdMAoZgLsJfrQ4eS/6u7DRf5UQgPh9aUv0cI4K74+ijYnfvDM4fyjfVqB56ryoely9Aocn08xlUFHX2k=
