export const SET_VISIBILITY_MENU = "SET_VISIBILITY_MENU";
export type SET_VISIBILITY_MENU = typeof SET_VISIBILITY_MENU;

export const GET_PICTURES = "GET_PICTURES";
export type GET_PICTURES = typeof GET_PICTURES;

export const FETCH_ERROR = "FETCH_ERROR";
export type FETCH_ERROR = typeof FETCH_ERROR;
