export const SET_VISIBILITY_MENU = "SET_VISIBILITY_MENU";
export type SET_VISIBILITY_MENU = typeof SET_VISIBILITY_MENU;
export const SET_VISIBILITY_UPLOAD_MODAL = "SET_VISIBILITY_UPLOAD_MODAL";
export type SET_VISIBILITY_UPLOAD_MODAL = typeof SET_VISIBILITY_UPLOAD_MODAL;
